/**
 * Firestore real-time messaging layer.
 *
 * Provides real-time listeners and send functions for:
 *  - Direct messages  (collection: direct_messages/{conversationId}/messages)
 *  - Group chat       (collection: group_messages/{projectId}/messages)
 *
 * Conversation IDs for DMs are derived by sorting both user IDs alphabetically
 * and joining with '_', so the same conversation doc is always found regardless
 * of which user initiates.
 */

import {
  collection,
  addDoc,
  onSnapshot,
  query,
  orderBy,
  updateDoc,
  doc,
  Unsubscribe,
  Timestamp,
  serverTimestamp,
} from 'firebase/firestore';
import { db } from './firebase';
import { Message, ProjectGroupMessage } from '../models/types';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Deterministic conversation ID for a DM thread between two users. */
export function dmConversationId(userId1: string, userId2: string): string {
  return [userId1, userId2].sort().join('_');
}

/** Convert a Firestore document snapshot to a plain JS object with an `id` field. */
function docToData<T>(snapshot: { id: string; data: () => any }): T {
  const data = snapshot.data();
  // Convert Firestore Timestamps to ISO strings so the rest of the app
  // can keep using string-based timestamp comparisons.
  if (data?.timestamp instanceof Timestamp) {
    data.timestamp = data.timestamp.toDate().toISOString();
  }
  return { id: snapshot.id, ...data } as T;
}

// ─── Direct Messages ─────────────────────────────────────────────────────────

/**
 * Subscribe to real-time updates for a DM thread between two users.
 * The callback is called immediately with existing messages and again
 * whenever a new message is added or an existing one changes.
 *
 * @returns An unsubscribe function — call it when the component unmounts.
 */
export function subscribeToDirectMessages(
  userId1: string,
  userId2: string,
  callback: (messages: Message[]) => void
): Unsubscribe {
  const convId = dmConversationId(userId1, userId2);
  const messagesRef = collection(db, 'direct_messages', convId, 'messages');
  const q = query(messagesRef, orderBy('timestamp', 'asc'));

  return onSnapshot(q, (snapshot) => {
    const messages = snapshot.docs.map((d) => docToData<Message>(d));
    callback(messages);
  });
}

/**
 * Send a direct message and save it to Firestore.
 * The `id` field is auto-generated by Firestore.
 */
export async function sendDirectMessage(
  message: Omit<Message, 'id'>
): Promise<void> {
  const convId = dmConversationId(message.senderId, message.recipientId);
  const messagesRef = collection(db, 'direct_messages', convId, 'messages');
  await addDoc(messagesRef, {
    ...message,
    timestamp: serverTimestamp(),
    read: false,
  });
}

/**
 * Mark a direct message as read.
 */
export async function markDirectMessageReadFirestore(
  messageId: string,
  senderId: string,
  recipientId: string
): Promise<void> {
  const convId = dmConversationId(senderId, recipientId);
  const messageRef = doc(db, 'direct_messages', convId, 'messages', messageId);
  await updateDoc(messageRef, { read: true });
}

// ─── Group Chat ───────────────────────────────────────────────────────────────

/**
 * Subscribe to real-time updates for a project group chat.
 * The callback is called immediately with existing messages and again
 * whenever a new message is added or changed.
 *
 * @returns An unsubscribe function — call it when the component unmounts.
 */
export function subscribeToGroupMessages(
  projectId: string,
  callback: (messages: ProjectGroupMessage[]) => void
): Unsubscribe {
  const messagesRef = collection(db, 'group_messages', projectId, 'messages');
  const q = query(messagesRef, orderBy('timestamp', 'asc'));

  return onSnapshot(q, (snapshot) => {
    const messages = snapshot.docs.map((d) => docToData<ProjectGroupMessage>(d));
    callback(messages);
  });
}

/**
 * Send a message to a project group chat and save it to Firestore.
 */
export async function sendGroupMessage(
  message: Omit<ProjectGroupMessage, 'id'>
): Promise<void> {
  const messagesRef = collection(db, 'group_messages', message.projectId, 'messages');
  await addDoc(messagesRef, {
    ...message,
    timestamp: serverTimestamp(),
  });
}
