/**
 * Firestore real-time messaging layer.
 *
 * Provides real-time listeners and send functions for:
 *  - Direct messages  (collection: direct_messages/{conversationId}/messages)
 *  - Group chat       (collection: group_messages/{projectId}/messages)
 *
 * Conversation IDs for DMs are derived by sorting both user IDs alphabetically
 * and joining with '_', so the same conversation doc is always found regardless
 * of which user initiates.
 */

import {
  collection,
  collectionGroup,
  addDoc,
  getDocs,
  onSnapshot,
  query,
  orderBy,
  where,
  updateDoc,
  doc,
  Unsubscribe,
  Timestamp,
  serverTimestamp,
} from 'firebase/firestore';
import { db } from './firebase';
import { Message, ProjectGroupMessage } from '../models/types';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Deterministic conversation ID for a DM thread between two users. */
export function dmConversationId(userId1: string, userId2: string): string {
  return [userId1, userId2].sort().join('_');
}

/** Convert a Firestore document snapshot to a plain JS object with an `id` field. */
function docToData<T>(snapshot: { id: string; data: () => any }): T {
  const data = snapshot.data();
  // Convert Firestore Timestamps to ISO strings so the rest of the app
  // can keep using string-based timestamp comparisons.
  if (data?.timestamp instanceof Timestamp) {
    data.timestamp = data.timestamp.toDate().toISOString();
  }
  return { ...data, id: snapshot.id } as T;
}

// ─── Direct Messages ─────────────────────────────────────────────────────────

/**
 * Subscribe to real-time updates for a DM thread between two users.
 * The callback is called immediately with existing messages and again
 * whenever a new message is added or an existing one changes.
 *
 * @returns An unsubscribe function — call it when the component unmounts.
 */
export function subscribeToDirectMessages(
  userId1: string,
  userId2: string,
  callback: (messages: Message[]) => void
): Unsubscribe {
  const convId = dmConversationId(userId1, userId2);
  const messagesRef = collection(db, 'direct_messages', convId, 'messages');
  const q = query(messagesRef, orderBy('timestamp', 'asc'));

  return onSnapshot(q, (snapshot) => {
    const messages = snapshot.docs.map((d) => docToData<Message>(d));
    callback(messages);
  });
}

/**
 * Read all direct messages where the user is either the sender or recipient.
 * Firestore does not support an OR across two fields without a composite query,
 * so we run two collection-group queries and merge the results client-side.
 */
export async function getDirectMessagesForUser(userId: string): Promise<Message[]> {
  const sentQuery = query(
    collectionGroup(db, 'messages'),
    where('senderId', '==', userId)
  );
  const receivedQuery = query(
    collectionGroup(db, 'messages'),
    where('recipientId', '==', userId)
  );

  const snapshots = await Promise.all([
    getDocs(sentQuery),
    getDocs(receivedQuery),
  ]);

  const messageMap = new Map<string, Message>();
  snapshots.forEach(snapshot =>
    snapshot.docs.forEach(documentSnapshot => {
      messageMap.set(documentSnapshot.ref.path, docToData<Message>(documentSnapshot));
    })
  );

  return Array.from(messageMap.values()).sort(
    (left, right) => new Date(left.timestamp).getTime() - new Date(right.timestamp).getTime()
  );
}

/** Helper to add a timeout to any promise */
function withTimeout<T>(promise: Promise<T>, timeoutMs = 10000, errorMsg = 'Message request timed out'): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(errorMsg)), timeoutMs)
    ),
  ]);
}

/**
 * Send a direct message and save it to Firestore.
 * The `id` field is auto-generated by Firestore.
 */
export async function sendDirectMessage(
  message: Omit<Message, 'id'>
): Promise<void> {
  const convId = dmConversationId(message.senderId, message.recipientId);
  const messagesRef = collection(db, 'direct_messages', convId, 'messages');
  const { id: _ignoredId, ...messageData } = message as Message;
  await withTimeout(
    addDoc(messagesRef, {
      ...messageData,
      timestamp: serverTimestamp(),
      read: false,
    }),
    12000,
    'Failed to deliver direct message within 12 seconds. Please check your internet connection.'
  );
}

/**
 * Mark a direct message as read.
 */
export async function markDirectMessageReadFirestore(
  messageId: string,
  senderId: string,
  recipientId: string
): Promise<void> {
  const convId = dmConversationId(senderId, recipientId);
  const messageRef = doc(db, 'direct_messages', convId, 'messages', messageId);
  await updateDoc(messageRef, { read: true }).catch(() => {});
}

// ─── Group Chat ───────────────────────────────────────────────────────────────

/**
 * Subscribe to real-time updates for a project group chat.
 * The callback is called immediately with existing messages and again
 * whenever a new message is added or changed.
 *
 * @returns An unsubscribe function — call it when the component unmounts.
 */
export function subscribeToGroupMessages(
  projectId: string,
  callback: (messages: ProjectGroupMessage[]) => void
): Unsubscribe {
  const messagesRef = collection(db, 'group_messages', projectId, 'messages');
  const q = query(messagesRef, orderBy('timestamp', 'asc'));

  return onSnapshot(q, (snapshot) => {
    const messages = snapshot.docs.map((d) => docToData<ProjectGroupMessage>(d));
    callback(messages);
  });
}

/**
 * Send a message to a project group chat and save it to Firestore.
 */
export async function sendGroupMessage(
  message: Omit<ProjectGroupMessage, 'id'>
): Promise<void> {
  const messagesRef = collection(db, 'group_messages', message.projectId, 'messages');
  const { id: _ignoredId, ...messageData } = message as ProjectGroupMessage;
  await withTimeout(
    addDoc(messagesRef, {
      ...messageData,
      timestamp: serverTimestamp(),
    }),
    12000,
    'Failed to deliver group message within 12 seconds. Please check your internet connection.'
  );
}
